### PR TITLE
Improving WordPress support

### PR DESCRIPTION
**Pull request by graham73may**
## The Issue
https://github.com/ddev/ddev-browsersync/issues/51

## How This PR Solves The Issue
This PR aims to replicate a similar approach used by ddev-redis to modify the project's CMS config.

## Manual Testing Instructions
1. `ddev start` a test project
2. Install the add on fork `ddev get ~/folder-of-fork/ddev-browsersync`
3. Start browsersync with `ddev browsersync` 
4. Open browsersync in your browser `ddev launch :3000`

WordPress should recognise the URL and load the page at port 3000 correctly.

## Related Issue Link(s)
https://github.com/ddev/ddev-browsersync/issues/51

### CODE REVIEW

**Comment by graham73may** [comment]
@rfay Do you have any advice on how the add-on install process executes and how this relates to if wp-config-ddev.php exists? 

I'm using `awk` to find `/** WP_HOME URL */` in `wp-config-ddev.php` here:

image

Running ddev get using my fork I'm getting this error, as if it can't find the ddev wp config:

image

**Comment by graham73may** [comment]
Spotted the issue, I need to add `${DDEV_APPROOT}` to all the file references

**Comment by tyler36** [comment]
Thank you for the PR. Please click "Ready for review" when you feel its good to go.

**Comment by graham73may** [comment]
Doing some testing on a project I've never used ddev-browsersync on and it did install and "just work™️". 

image

Marking this PR as ready for review.

Thanks!

**Comment by graham73may** [comment]
The project I tested with didn't have `#ddev-generated:` in the `wp-config-ddev.php` file (for other reasons). 

`wp-config-ddev.php` get's reset on each ddev restart if it is being controlled by ddev. 

@rfay Is there any post_start hook for add-ons? I'm guessing not based on this: https://ddev.readthedocs.io/en/stable/users/extend/additional-services/#creating-an-additional-service-for-ddev-get

The reason I put the include in `wp-config-ddev.php` is because that's where the `WP_HOME` and `WP_SITEURL` are loading from, so it felt most relevant to put the browsersync code close to that incase you're debugging a site URL issue.  

Maybe I need to refactor things to add the include early on in the `wp-config.php` file.

**Comment by graham73may** [comment]
Maybe this placement is preferable? 

image

**Comment by tyler36** [comment]
Thank you for the PR. I gave it a quick run through but not knowing WP that well, it made it hard to tell what works, and what doesn't.

## Test

1. Install addon
2. Start browsersync.

```shell
ddev browsersync
```

3. Visit browsersync proxy page as shown in terminal (Eg. https://wp-vanilla.ddev.site:3000)
4. Visit login page: https://wp-vanilla.ddev.site:3000/wp-admin

This takes me to: `https://wp-vanilla.ddev.site/wp-login.php?redirect_to=https%3A%2F%2Flocalhost%2Fwp-admin%2F&reauth=1`

2 things of note here:

- This base URL no longer contains `3000` port.
- The redirect to URL does not contain `3000` port.

So WP seems to be losing the port number. Am I missing something?

**Comment by graham73may** [comment]
Is your wp-vanilla project a repo I could see? Particularly interested in wp-config.php, wp-config-ddev.php and any other config files you may have. 

Also unsure where you’re getting localhost from in the redirect_to value!

**Comment by tyler36** [comment]
Thank you for the quick reply @graham73may .

I just just the site again and I'm _not_ getting `localhost` in the redirect URl (not sure how to replicate it).

Anyway, here is the repo I was using to test. It's a WP site following DDEV quickstart guide, with your PR added `browsersync` branch.

**Comment by graham73may** [comment]
Hi @tyler36 thanks for taking the time to test it!

I've been testing using the DDEV WP quickstart and it's working mostly as I'd expect. 

These are the steps I followed, all working as expected focusing on the frontend:

```
git clone

ddev start

ddev wp core download

ddev wp core install --url='$DDEV_PRIMARY_URL' --title='wp-vanilla' --admin_user=admin --admin_email=admin@example.com --prompt=admin_password

ddev launch

# => I see a working WordPress website

# Now to Install ddev-browsersync, obviously use your own folder or .gz for my PR here!
ddev get ~/Repos/ddev-browsersync

# Start browsersync to activate port 3000
ddev browsersync

# Launch on port 3000 (This is where the ddev quickstart tries to take you to the admin area. I'm going to the frontend).
ddev launch :3000
```

Now, looking at the admin area specifically - I've not dug too deep but it seems when WordPress redirects you as an unauthenticated user from `/wp-admin/` to `/wp-login.php` it strips the port. 

This might just be my opinion, but if you're using browsersync on WordPress, you're probably developing a frontend theme... So I'm not sure how much I'm willing to go down this rabbit hole. If you're customizing the backend in WordPress I think it's fair enough to expect them to have to login and then go to port 3000... 

Some more notes on testing `ddev launch :3000/wp-admin`:

```
# Strips the port
ddev launch :3000 /wp-admin

# Even if I try this it strips the port:
ddev launch https://wp-vanilla.ddev.site:3000/wp-admin
```

However, if you don't use the `/wp-admin` URL shortcut to reach the login page (which triggers a redirect) you can load the login form on port 3000 using this, going directly to the login form: 
```
ddev launch :3000/wp-login.php
```

**Comment by tyler36** [comment]
@graham73may  

Thank you for the feedback and analysis. I remember people complaining aboout that type of issue with Drupal (or maybe Laravel?)  a long time ago. 

Things to do:

- fix resolve conflicts
- confirm uninstall works

If the PR works as intended and we can resolve those last couple of things, I'm happy to merge.

**Comment by graham73may** [comment]
1 - Conflicts resolved and pushed to PR

:3000 still working: 

image


2 - Uninstall was removing scripts but was leaving a couple of things, I've added a remove-wordpress-settings.sh file to do a better job of tidying up. (mainly inside wp-config.php). 

After installing: 
image

After removing (puts it back how it was): 
image

**Comment by tyler36** [comment]
Thank you for your patience. I didn't get a chance to look at this till today.

- [X] Confirm uninstall works

```
$ ddev get https://github.com/graham73may/ddev-browsersync/tarball/feature_wp-config 
...
$ ddev get --remove https://github.com/graham73may/ddev-browsersync/tarball/feature_wp-config 
Removing wp-config-ddev-browsersync.php from: /home/user13/code/framework/wp-vanilla/wp-config.php

👍 Remove browsersync settings for WordPress if applicable
Removed add-on https://github.com/graham73may/ddev-browsersync/tarball/feature_wp-config
```

- [X] Merge conflicts resolved.

I just kicked off the test pipeline. Will merge and release when they pass.

**Comment by tyler36** [comment]
Thank you for the contribution!

**Pull request merged**
